### ISSUE TITLE
Failure to build with G++ version 15.0

### ISSUE THREAD

**Issue by sham1** [herbstluftwm/herbstluftwm#1612]
Currently on Fedora Rawhide and 42, building Herbstluftwm 0.9.5 fails due to the following error within `xconnection.cpp`:

```
/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/src/xconnection.cpp: In function ‘std::string iso_8859_1_to_utf8(const char*)’:
/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/src/xconnection.cpp:295:9: error: ‘uint8_t’ was not declared in this scope
  295 |         uint8_t ch = source[i];
      |         ^~~~~~~
/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/src/xconnection.cpp:15:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
   14 | #include "globals.h"
  +++ |+#include <cstdint>
   15 | 
/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/src/xconnection.cpp:296:13: error: ‘ch’ was not declared in this scope
  296 |         if (ch < 0x80) {
      |             ^~
gmake[2]: *** [src/CMakeFiles/herbstluftwm.dir/build.make:894: src/CMakeFiles/herbstluftwm.dir/xconnection.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/redhat-linux-build'
gmake[1]: *** [CMakeFiles/Makefile2:228: src/CMakeFiles/herbstluftwm.dir/all] Error 2
gmake[1]: Leaving directory '/builddir/build/BUILD/herbstluftwm-0.9.5-build/herbstluftwm-0.9.5/redhat-linux-build'
gmake: *** [Makefile:139: all] Error 2
```

Simple fix is to add `cstdint` onto the file, as suggested by the error message. I'm just wondering if it should be included within `xconnection.cpp` or some kind of a header file instead.
